### PR TITLE
Add Optional Scroll Controller

### PR DESCRIPTION
**Pull request by OUFA217**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing using `flutter test`

If you need help, consider pinging the maintainer @maheshj01

[Contributor Guide]: https://github.com/maheshj01/searchfield/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by OUFA217** [comment]
Can you check again now?

**Comment by maheshj01** [comment]
Rebase the master branch to fix this test failure.

**Comment by OUFA217** [comment]
Can you check again?

**Comment by maheshj01** [comment]
Thank you for your contribution.

**Pull request merged**
